sudo: false
language: d
addons:
 apt:
  sources:
   - mono
  packages:
   - mono-devel
d:
 - dmd
 - ldc
env:
 - DUBCONF=mono-dynamic
 - DUBCONF=mono-static-test
script:
 - dub upgrade
 - dub test --compiler=${DC} --config=${DUBCONF}
